spring:
  datasource:
    url: jdbc:mysql://cdb-lob0ggj0.bj.tencentcdb.com:10048/commonMall?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: clj123456@
  redis:
    host: 192.168.1.134
    password: 123
upload:
  imgSavePath: "C:/upload/img"
  fileSavePath: "C:/upload/file"
